### PR TITLE
Add a FileField and MultipleDocumentSelectField and allow passing of kwargs to fields

### PR DESCRIPTION
**Pull request by jschrewe**
These commits add a FileField and a multiple select field that works with mongoengine Listfields which contain reference fields.

Additionally kwargs passed to generate are passed through to the field constructor.

### CODE REVIEW

**Comment by wpjunior** [comment]
thanks @jschrewe

**Comment by wpjunior** [comment]
if you can add as examples in the test project;

**Comment by jschrewe** [comment]
Umm, add what exactly?

**Comment by wpjunior** [comment]
examples of use FileField, and others added by you

**Comment by jschrewe** [comment]
Sorry for getting back to you so late. I'm a bit short on time. I'll look into adding examples his weekend (hopefully).

**Pull request merged**
